version: '3'

services:
  app:
    build: .
    volumes:
      - ./app:/app
    command: gunicorn main:app -b :8080 --worker-class aiohttp.GunicornWebWorker --reload --access-logfile -
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"